### ISSUE TITLE
device spec to run the  inference

### ISSUE THREAD

**Issue by adelightday** [FreedomIntelligence/LongLLaVA#8]
Hello, appreciate your great work! I have read your paper. I'm a new learner and plan to run LongLLaVA locally. Do you have any minimum specifications for devices to run the inference?

Thank you for considering my question.

**Comment by adelightday** [comment]
Is it possible to run the inference for 13B parameters without a GPU? Could a CPU with high memory such as 32GB  be enough? As far as I know, LLaVA is capable of running without GPU. If LongLLaVA is only compatible with GPU, could you please explain why?

Thank you!

**Comment by wangxidong06** [comment]
Sorry for the delayed response, I was on vacation this past week.

Regarding the minimum equipment needed to run the model, for the MoE model you will probably need at least 80GB of RAM, but in the latest paper we have also trained the Dense model (9B), which will probably only need 24GB of RAM to run, the model will be released soon (within two days) so please stay tuned.

As for the CPU not working, since we haven't tried it before, we don't know why, maybe not enough RAM, we'll get back to you after we try it.

For the smallest device needed to experience the architecture, we also plan to train and release a series of small models of 0.5B, 1.5B, 3.8B and so on (within 3-4 weeks) to minimize the barriers to use.

**Comment by adelightday** [comment]
Hi, thank you for the clear explanation. Looking forward to the updated model!

**Comment by wangxidong06** [comment]
The 9B model is [here](https://huggingface.co/FreedomIntelligence/LongLLaVA-9B)
